// =============================================================================
// Jettison — the enforcement
// =============================================================================
// The architecture in one file. Five sections, readable top to bottom:
//
//   1. Layers         — imports flow one way: app → modules → shared → core
//   2. Module privacy — a module is reachable only through its index.ts
//   3. R1 (views)     — .tsx files render; they never fetch, dispatch, or navigate
//   4. R5 (services)  — business logic is React-free and store-free
//   5. Evidence       — TypeScript that keeps the type it was handed
//
// Every rule here ships as `error`. Warnings are wallpaper within a week.
//
// Copy this file into your own codebase: change the four alias-to-folder pairs in
// tools/oxlint/jettison/index.ts to match your layout and the rest follows.
//
// Sections 1 and 2 are a local plugin because no linter ships them: they are the
// one part of this config that is genuinely ours. Section 5 is vendored.
//
// A config that matches nothing is indistinguishable from one that is satisfied —
// so `fixtures/` holds a deliberately violating file per rule group, and
// `fixtures/enforcement.test.ts` asserts in CI that each rule fires.
// =============================================================================
import { defineConfig } from 'oxlint';

/** Files whose whole job is to decide something — R5 applies to all of them. */
const SERVICE_FILES = ['**/services/**/*.ts', '**/*-rules.ts', '**/*-eligibility.ts'];

/** R1's one exemption: something has to mount the store and the router. A two-file
    allowlist, not a folder — `src/app` is full of layouts and screens R1 polices. */
const COMPOSITION_ROOT = ['src/main.tsx', 'src/app/providers.tsx'];

export default defineConfig({
  ignorePatterns: [
    'dist/**',
    'coverage/**',
    'node_modules/**',
    // Generated by `msw init`, vendored verbatim.
    'public/mockServiceWorker.js',
    // Not application source: agent tooling and the two vendored plugins.
    '.claude/**',
    'tools/oxlint/anti-slop/**',
  ],

  jsPlugins: [
    { name: 'jettison', specifier: './tools/oxlint/jettison/index.ts' },
    { name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' },
  ],

  // The hooks rules are correctness insurance; the sections below are the
  // architecture. `typescript`, `unicorn` and `oxc` are on by default.
  plugins: ['react', 'typescript', 'unicorn', 'oxc'],
  categories: { correctness: 'error' },

  rules: {
    'react/exhaustive-deps': 'error',
    'react/rules-of-hooks': 'error',

    // ==========================================================================
    // 1. LAYERS — app → modules → shared → core, and never the other way
    // 2. MODULE PRIVACY — index.ts is the only door
    // ==========================================================================
    // Both read off the file's own path (see the plugin). Folders that have not
    // adopted the layout stay unconstrained, so this config can be dropped into a
    // migration without a red build on day one. Every adopted folder is a ratchet.
    'jettison/layer-dependencies': 'error',
    'jettison/module-privacy': 'error',

    // The baseline typescript-eslint recommends, minus what `correctness` already
    // covers. Type-aware rules are deliberately absent: this config runs on every
    // save, and `npm run type-check` owns the slow, whole-program truth.
    'typescript/ban-ts-comment': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/triple-slash-reference': 'error',

    // ==========================================================================
    // 5. EVIDENCE — no unknown at the boundary, no laundered assertion
    // ==========================================================================
    // Vendored from the anti-slop plugin. These are about the *type* a value
    // carries, not about where the file sits: an `unknown` parameter or an
    // unexplained `as` is how a contract quietly stops being one.
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
  },

  overrides: [
    // ==========================================================================
    // 3. R1 — VIEWS RENDER
    // ==========================================================================
    // A .tsx file may import React, styles, design-system and child components,
    // its own colocated hook, and types. Never a query, a store, an HTTP client,
    // or a navigator: navigation is a handler, and handlers come from the hook.
    //
    // Type-only imports are allowed — a view is welcome to know the shape of its
    // props. It is the *runtime* reach that is banned.
    {
      files: ['**/*.tsx'],
      rules: {
        'no-restricted-imports': [
          'error',
          {
            paths: [
              {
                name: 'react-redux',
                allowTypeImports: true,
                message: 'R1: a view never touches the store — move it to the colocated hook.',
              },
              {
                name: 'react-router',
                importNames: ['useNavigate'],
                message: 'R1: navigation is a handler — the hook returns it, the view calls it.',
              },
              {
                name: 'react-router-dom',
                importNames: ['useNavigate'],
                message: 'R1: navigation is a handler — the hook returns it, the view calls it.',
              },
              {
                name: 'axios',
                allowTypeImports: true,
                message: 'R1: a view never speaks HTTP — data arrives through its hook.',
              },
            ],
            patterns: [
              {
                group: ['**/api', '**/api/*', '@core/api', '@core/api/*'],
                allowTypeImports: true,
                message: 'R1: a view never imports endpoints — its colocated hook does.',
              },
              {
                group: ['@app/*'],
                allowTypeImports: true,
                message: 'R1: a view never reaches into the app shell (store, router, providers).',
              },
            ],
          },
        ],
      },
    },

    { files: COMPOSITION_ROOT, rules: { 'no-restricted-imports': 'off' } },

    // ==========================================================================
    // 4. R5 — SERVICES DECIDE
    // ==========================================================================
    // Services are where the money-losing bugs live, so they are kept trivially
    // testable: plain functions, no React, no store, no router, no fetching.
    // Input object in, issue codes out — no mocks, no DOM.
    {
      files: SERVICE_FILES,
      rules: {
        'no-restricted-imports': [
          'error',
          {
            patterns: [
              {
                group: ['react', 'react-*', '@reduxjs/*', 'react-router*'],
                allowTypeImports: true,
                message: 'R5: services are React-free and store-free — plain functions only.',
              },
              {
                group: ['@app/*', '**/api', '**/api/*', '@core/api', '@core/api/*'],
                allowTypeImports: true,
                message:
                  'R5: a service decides, it does not fetch — pass the data in as arguments.',
              },
            ],
          },
        ],
      },
    },

    // The simulated backend is the app's fixture, not its source: it fabricates the
    // data and then asserts on JSON it produced itself, so the five section-5 rules
    // below would only have it parse its own seeds. Every other rule still
    // applies — sections 1–4 police this folder like any other.
    {
      files: ['src/mocks/**'],
      rules: {
        'anti-slop/no-conditional-empty-object-spread': 'off',
        'anti-slop/no-known-value-widening': 'off',
        'anti-slop/no-module-mocking': 'off',
        'anti-slop/no-unknown-parameters': 'off',
        'anti-slop/require-safety-comment-for-type-assertion': 'off',
      },
    },
  ],
});
